### ISSUE TITLE
Github "Discussions"

### ISSUE THREAD

**Issue by petermr** [mitko/readable_climate_reports#1]
I find it very useful to have a Github Discussions. Not sure who can open these - probably has to be project owner. I think they allow any Github user to contribute which saves having to add people just for this purose

**Comment by mitko** [comment]
Yes! Do you mean GH Issues?  I've used GH Issues quite a lot in my previous job - think they are awesome.
I can also suggest some tools for working with them.

**Comment by petermr** [comment]
No , discussions, see my DM

**Comment by mitko** [comment]
Done - https://github.com/mitko/readable_climate_reports/discussions
